stages:
  - build
  - package


.build_template: &build_template
  stage: build
  before_script:
    - "rm -rf build/"
  script:
    - make LANG=$LANGUAGE $DOCUMENT.html
    - echo "Searching for build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.$FILEEXT"
    - test -e build/$FORMAT/$LANGUAGE/$DOCUMENT/$DOCUMENT.$FILEEXT
  artifacts:
    paths:
      - build/$FORMAT/$LANGUAGE/$DOCUMENT/$DOCUMENT.$FILEEXT
    expire_in: 1 hour

de-getting-started-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1
    FORMAT: xhtml
    FILEEXT: html


en-getting-started-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1
    FORMAT: xhtml
    FILEEXT: html

de-manual-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1
    FORMAT: xhtml
    FILEEXT: html

en-manual-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1
    FORMAT: xhtml
    FILEEXT: html

de-winst-manual:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual
    FORMAT: xhtml
    FILEEXT: html

en-winst-manual:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual
    FORMAT: xhtml
    FILEEXT: html


package_docs:
  stage: package
  script:
    - make publish
  artifacts:
    paths:
      - pub/
    expire_in: 3 days
  only:
    - stable
