stages:
  - build
  - package

# per document-type job templates
.build_template_html: &build_template_html
  stage: build
  script:
    - make LANG=$LANGUAGE $DOCUMENT.html
    - test -f build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html
  artifacts:
    paths:
      - build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html
    expire_in: 1 hour

.build_template_epub: &build_template_epub
  stage: build
  script:
    - make LANG=$LANGUAGE $DOCUMENT.epub
    - test -f build/epub/$LANGUAGE/$DOCUMENT/$DOCUMENT.epub
  artifacts:
    paths:
      - build/epub/$LANGUAGE/$DOCUMENT/$DOCUMENT.epub
    expire_in: 1 hour

.build_template_pdf: &build_template_epub
  stage: build
  script:
    - make LANG=$LANGUAGE $DOCUMENT.pdf
    - test -f build/pdf/$LANGUAGE/$DOCUMENT/$DOCUMENT.pdf
  artifacts:
    paths:
      - build/pdf/$LANGUAGE/$DOCUMENT/$DOCUMENT.pdf
    expire_in: 1 hour


# - HTML build jobs -
de-html-getting-started-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1

en-html-getting-started-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1

de-html-manual-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1

en-html-manual-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1

de-html-winst-manual:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

en-html-winst-manual:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual

# - epub build jobs -
de-epub-getting-started-v4.1:
  <<: *build_template_epub
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1

en-epub-getting-started-v4.1:
  <<: *build_template_epub
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1

de-epub-manual-v4.1:
  <<: *build_template_epub
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1

en-epub-manual-v4.1:
  <<: *build_template_epub
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1

de-epub-winst-manual:
  <<: *build_template_epub
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

# - pdf build jobs -
de-pdf-getting-started-v4.1:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1

en-pdf-getting-started-v4.1:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1

de-pdf-manual-v4.1:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1

en-pdf-manual-v4.1:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1

de-pdf-winst-manual:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

package_docs:
  stage: package
  script:
    - make publish
  artifacts:
    paths:
      - pub/
    expire_in: 3 days
  only:
    - stable
