.build_template: &build_template
  before_script:
    - "rm -rf build/"
  script:
    - make LANG=$LANGUAGE $DOCUMENT.html
    - echo "Searching for build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.$FORMAT"
    - test -e build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.$FORMAT
  artifacts:
    paths:
      - build/$FORMAT/$LANGUAGE/$DOCUMENT/$DOCUMENT.$FORMAT
    expire_in: 1 hour

de-getting-started-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1
    FORMAT: html

en-getting-started-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1
    FORMAT: html

de-manual-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1
    FORMAT: html

en-manual-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1
    FORMAT: html

de-winst-manual:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual
    FORMAT: html

en-winst-manual:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual
    FORMAT: html
