image: docker.uib.local/opsi/opsidoc-builder

stages:
  - build
  - test

build_docu:
  stage: build
  script:
    - python3 tools/create_docu.py
  

# - HTML build jobs -
.test_template: &test_template
  stage: test
  script:
    - test -f build/$FORMAT/$LANGUAGE/$DOCUMENT/$DOCUMENT.html
  artifacts:
    paths:
      - build/html/$LANGUAGE/$DOCUMENT/*
    expire_in: 2 days


en-html-getting-started-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.2
    FORMAT: html

de-html-manual-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.2
    FORMAT: html

en-html-manual-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.2
    FORMAT: html

de-html-winst-manual:
  <<: *test_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual
    FORMAT: html

en-html-winst-manual:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual
    FORMAT: html

en-html-winst-reference-card:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-reference-card
    FORMAT: html

# de-html-releasenotes-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-v4.2-releasenotes

en-html-releasenotes-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-v4.2-releasenotes
    FORMAT: html

de-html-supportmatrix:
  <<: *test_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-supportmatrix
    FORMAT: html

en-html-supportmatrix:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-supportmatrix
    FORMAT: html

# - pdf build jobs -
de-pdf-getting-started-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.2
    FORMAT: pdf

en-pdf-getting-started-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.2
    FORMAT: pdf

de-pdf-manual-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.2
    FORMAT: pdf

en-pdf-manual-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.2
    FORMAT: pdf

de-pdf-winst-manual:
  <<: *test_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual
    FORMAT: pdf

en-pdf-winst-manual:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual
    FORMAT: pdf

en-pdf-winst-reference-card:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-reference-card
    FORMAT: pdf

# de-pdf-releasenotes-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-v4.2-releasenotes

en-pdf-releasenotes-v4.2:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-v4.2-releasenotes
de-pdf-supportmatrix:
  <<: *test_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-supportmatrix

en-pdf-supportmatrix:
  <<: *test_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-supportmatrix




# per document-type job templates
# .test_template: &test_template
#   stage: build
#   script:
#     - make DEBUG=1 LANG=$LANGUAGE $DOCUMENT.html
#     - test -f build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html
#   artifacts:
#     paths:
#       - build/xhtml/$LANGUAGE/$DOCUMENT/*
#     expire_in: 2 days

# .build_template_epub: &build_template_epub
#   stage: build
#   script:
#     - make LANG=$LANGUAGE $DOCUMENT.epub
#     - test -f build/epub/$LANGUAGE/$DOCUMENT/$DOCUMENT.epub
#   artifacts:
#     paths:
#       - build/epub/$LANGUAGE/$DOCUMENT/$DOCUMENT.epub
#     expire_in: 2 days

# .test_template: &test_template
#   stage: build
#   script:
#     - make LANG=$LANGUAGE $DOCUMENT.pdf
#     - test -f build/pdf/$LANGUAGE/$DOCUMENT/$DOCUMENT.pdf
#   artifacts:
#     paths:
#       - build/pdf/$LANGUAGE/$DOCUMENT/$DOCUMENT.pdf
#     expire_in: 2 days


# # - HTML build jobs -
# de-html-getting-started-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-getting-started-v4.2

# en-html-getting-started-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-getting-started-v4.2

# de-html-manual-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-manual-v4.2

# en-html-manual-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-manual-v4.2

# de-html-winst-manual:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-winst-manual

# en-html-winst-manual:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-winst-manual

# en-html-winst-reference-card:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-winst-reference-card

# # de-html-releasenotes-v4.2:
# #   <<: *test_template
# #   variables:
# #     LANGUAGE: de
# #     DOCUMENT: opsi-v4.2-releasenotes

# en-html-releasenotes-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-v4.2-releasenotes
# de-html-supportmatrix:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-supportmatrix

# en-html-supportmatrix:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-supportmatrix


# # - epub build jobs -
# de-epub-getting-started-v4.2:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-getting-started-v4.2

# en-epub-getting-started-v4.2:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-getting-started-v4.2

# de-epub-manual-v4.2:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-manual-v4.2

# en-epub-manual-v4.2:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-manual-v4.2

# de-epub-winst-manual:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-winst-manual

# en-epub-winst-manual:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-winst-manual

# en-epub-winst-reference-card:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-winst-reference-card

# # de-epub-releasenotes-v4.2:
# #   <<: *build_template_epub
# #   variables:
# #     LANGUAGE: de
# #     DOCUMENT: opsi-v4.2-releasenotes

# en-epub-releasenotes-v4.2:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-v4.2-releasenotes
# de-epub-supportmatrix:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-supportmatrix

# en-epub-supportmatrix:
#   <<: *build_template_epub
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-supportmatrix


# # - pdf build jobs -
# de-pdf-getting-started-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-getting-started-v4.2

# en-pdf-getting-started-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-getting-started-v4.2

# de-pdf-manual-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-manual-v4.2

# en-pdf-manual-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-manual-v4.2

# de-pdf-winst-manual:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-winst-manual

# en-pdf-winst-manual:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-winst-manual

# en-pdf-winst-reference-card:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-winst-reference-card

# # de-pdf-releasenotes-v4.2:
# #   <<: *test_template
# #   variables:
# #     LANGUAGE: de
# #     DOCUMENT: opsi-v4.2-releasenotes

# en-pdf-releasenotes-v4.2:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-v4.2-releasenotes
# de-pdf-supportmatrix:
#   <<: *test_template
#   variables:
#     LANGUAGE: de
#     DOCUMENT: opsi-supportmatrix

# en-pdf-supportmatrix:
#   <<: *test_template
#   variables:
#     LANGUAGE: en
#     DOCUMENT: opsi-supportmatrix


# # Packaging and renaming of documents
# package_docs:
#   stage: package
#   script:
#     - make publish
#   artifacts:
#     paths:
#       - pub/
#     expire_in: 7 days
#   only:
#     - stable


# # Publishing documentation to internal server
# publish_docs:
#   stage: publish
#   before_script:
#     - 'which ssh-agent || (apt update -y && apt install -y openssh-client)'
#     - mkdir -p ~/.ssh
#     - eval $(ssh-agent -s)
#     - ssh-add <(echo "$DOCUSER_PRIVATE_KEY")
#   script:
#     - scp -o StrictHostKeyChecking=no -r pub/* "$DOCUSER@$DOCSERVER:/home/opsi/doc/opsidoc/git-stable/"
#   only:
#     - stable
