.build_template: &build_template
  before_script:
    - "rm -rf build/"
  script:
    - make LANG=$LANGUAGE $DOCUMENT.html
    - echo "Searching for build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html"
    - test -e build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html

de-getting-started-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1

en-getting-started-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1

de-manual-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1

en-manual-v4.1:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1

de-winst-manual:
  <<: *build_template
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

en-winst-manual:
  <<: *build_template
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual
