# image: docker.uib.local/opsi/opsidoc-builder
image: asciidoctor/docker-asciidoctor

stages:
  - build
  - package
  - publish

# per document-type job templates
.build_template_html: &build_template_html
  stage: build
  script:
    - apk add ruby-dev
    - apk add build-base
    - apk add graphicsmagick-dev
    - gem install prawn-gmagick
    - gem install compass
    - gem install zurb-foundation --version 4.3.2
    - sh tools/build_stylesheets.sh
    - python3 tools/create_docu.py --lang $LANGUAGE --files $DOCUMENT --style opsi --output html 
    - test -f build/$LANGUAGE/html/$DOCUMENT/$DOCUMENT.html
  artifacts:
    paths:
      - build/$LANGUAGE/html/$DOCUMENT/*
    expire_in: 2 days

.build_template_pdf: &build_template_pdf
  stage: build
  script:
    - apk add ruby-dev
    - apk add build-base
    - apk add graphicsmagick-dev
    - gem install prawn-gmagick
    - python3 tools/create_docu.py --lang $LANGUAGE --files $DOCUMENT --theme conf/opsi-theme.yml --output pdf
    - test -f build/$LANGUAGE/pdf/$DOCUMENT/$DOCUMENT.pdf
  artifacts:
    paths:
      - build/$LANGUAGE/pdf/$DOCUMENT/*
    expire_in: 2 days


# - HTML build jobs -
de-html-getting-started-v4.2:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.2

en-html-getting-started-v4.2:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.2

de-html-manual-v4.2:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.2

en-html-manual-v4.2:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.2

de-html-winst-manual:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

en-html-winst-manual:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual

en-html-winst-reference-card:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-reference-card

en-html-releasenotes-v4.2:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-v4.2-releasenotes
de-html-supportmatrix:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-supportmatrix

en-html-supportmatrix:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-supportmatrix

# - pdf build jobs -
de-pdf-getting-started-v4.2:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.2

en-pdf-getting-started-v4.2:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.2

de-pdf-manual-v4.2:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.2

en-pdf-manual-v4.2:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.2

de-pdf-winst-manual:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

en-pdf-winst-manual:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual

en-pdf-winst-reference-card:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-reference-card

en-pdf-releasenotes-v4.2:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-v4.2-releasenotes
de-pdf-supportmatrix:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-supportmatrix

en-pdf-supportmatrix:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-supportmatrix


# Packaging and renaming of documents
# package_docs:
#   stage: package
#   script:
#     - make publish
#   artifacts:
#     paths:
#       - pub/
#     expire_in: 7 days
#   only:
#     - stable


# Publishing documentation to internal server
# publish_docs:
#   stage: publish
#   before_script:
#     - 'which ssh-agent || (apt update -y && apt install -y openssh-client)'
#     - mkdir -p ~/.ssh
#     - eval $(ssh-agent -s)
#     - ssh-add <(echo "$DOCUSER_PRIVATE_KEY")
#   script:
#     - scp -o StrictHostKeyChecking=no -r pub/* "$DOCUSER@$DOCSERVER:/home/opsi/doc/opsidoc/git-stable/"
#   only:
#     - stable
