image: docker.uib.gmbh/opsi/opsidoc-builder

stages:
  - build
  - package
  - publish
  - publish_ext

# per document-type job templates
.build_template_html: &build_template_html
  stage: build
  script:
    - make DEBUG=1 LANG=$LANGUAGE $DOCUMENT.html
    - test -f build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html
  artifacts:
    paths:
      - build/xhtml/$LANGUAGE/$DOCUMENT/*
    expire_in: 2 days

.build_template_epub: &build_template_epub
  stage: build
  script:
    - make LANG=$LANGUAGE $DOCUMENT.epub
    - test -f build/epub/$LANGUAGE/$DOCUMENT/$DOCUMENT.epub
  artifacts:
    paths:
      - build/epub/$LANGUAGE/$DOCUMENT/$DOCUMENT.epub
    expire_in: 2 days

.build_template_pdf: &build_template_pdf
  stage: build
  script:
    - make LANG=$LANGUAGE $DOCUMENT.pdf
    - test -f build/pdf/$LANGUAGE/$DOCUMENT/$DOCUMENT.pdf
  artifacts:
    paths:
      - build/pdf/$LANGUAGE/$DOCUMENT/$DOCUMENT.pdf
    expire_in: 2 days


# - HTML build jobs -
de-html-getting-started-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1

en-html-getting-started-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1

de-html-manual-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1

en-html-manual-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1

de-html-winst-manual:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

en-html-winst-manual:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual

en-html-winst-reference-card:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-reference-card

de-html-supportmatrix:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-supportmatrix

en-html-supportmatrix:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-supportmatrix


# - epub build jobs -
de-epub-getting-started-v4.1:
  <<: *build_template_epub
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1

en-epub-getting-started-v4.1:
  <<: *build_template_epub
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1

de-epub-manual-v4.1:
  <<: *build_template_epub
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1

en-epub-manual-v4.1:
  <<: *build_template_epub
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1

de-epub-winst-manual:
  <<: *build_template_epub
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

en-epub-winst-manual:
  <<: *build_template_epub
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual

en-epub-winst-reference-card:
  <<: *build_template_epub
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-reference-card

de-epub-supportmatrix:
  <<: *build_template_epub
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-supportmatrix

en-epub-supportmatrix:
  <<: *build_template_epub
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-supportmatrix


# - pdf build jobs -
de-pdf-getting-started-v4.1:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1

en-pdf-getting-started-v4.1:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1

de-pdf-manual-v4.1:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1

en-pdf-manual-v4.1:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1

de-pdf-winst-manual:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

en-pdf-winst-manual:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual

en-pdf-winst-reference-card:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-reference-card

de-pdf-supportmatrix:
  <<: *build_template_pdf
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-supportmatrix

en-pdf-supportmatrix:
  <<: *build_template_pdf
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-supportmatrix


# Packaging and renaming of documents
package_docs:
  stage: package
  script:
    - make publish
  artifacts:
    paths:
      - pub/
    expire_in: 7 days
  only:
    - stable


# Publishing documentation to internal server
publish_docs:
  stage: publish
  before_script:
    - 'which ssh-agent || (apt update -y && apt install -y openssh-client)'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DOCUSER_PRIVATE_KEY")
  script:
    - scp -o StrictHostKeyChecking=no -r pub/* "$DOCUSER@$DOCSERVER:/home/opsi/doc/opsidoc/git-stable/"
  only:
    - stable

# Publishing documentation to internal server
publish_docs_ext:
  stage: publish_ext
  when: manual
  before_script:
    - 'which ssh-agent || (apt update -y && apt install -y openssh-client)'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DOCUSER_PRIVATE_KEY")
  script:
    - scp -P 10022 -o StrictHostKeyChecking=no -r pub/* "$DOCUSER_EXT@$DOCSERVER_EXT:/var/www/opsi/htdocs/opsi4.1/$DOCTARGET/documentation/"
  only:
    - stable
