stages:
  - build
  - package


.build_template_html: &build_template_html
  stage: build
  before_script:
    - "rm -rf build/"
  script:
    - make LANG=$LANGUAGE $DOCUMENT.html
    - echo "Searching for build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html"
    - test -e build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html
  artifacts:
    paths:
      - build/xhtml/$LANGUAGE/$DOCUMENT/$DOCUMENT.html
    expire_in: 1 hour

# - HTML build jobs -
de-html-getting-started-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-getting-started-v4.1

en-html-getting-started-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-getting-started-v4.1

de-html-manual-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-manual-v4.1

en-html-manual-v4.1:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-manual-v4.1

de-html-winst-manual:
  <<: *build_template_html
  variables:
    LANGUAGE: de
    DOCUMENT: opsi-winst-manual

en-html-winst-manual:
  <<: *build_template_html
  variables:
    LANGUAGE: en
    DOCUMENT: opsi-winst-manual


package_docs:
  stage: package
  script:
    - make publish
  artifacts:
    paths:
      - pub/
    expire_in: 3 days
  only:
    - stable
