//// 
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.05.2011
:Revision:  4.0.1
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-introduction]]
== Introduction

[[opsi-manual-introduction-who-should-read]]
=== Who should read this manual?

This manual is for anyone interested in gaining deeper insight on the opsi software distribution platform (open pc server integration). The focus of the documentation is to provide a technical context of the processes involved.

This manual provides practical advice for the system administrator and the prospective customer looking for a concrete overview of opsi’s features.


[[opsi-manual-introduction-conventions]]
=== Notations

Replace names shown in '<angle brackets>' with the correct absolute or full path. 

Examples: 
 '<opsi-depot-share>' is the location of the opsi packages file share located at the `/var/lib/opsi/depot` path on your server.   

Likewise, the `<opsi-depot-share>/ooffice` software packet refers to the `/var/lib/opsi/depot/ooffice` path. 

Example snippets from program code or configuration files use Courier font with highlight:

[source,prompt]
----
depoturl=smb://smbhost/sharename/path
----
